name: Amazing Frontend

on: [push]

jobs:
  Scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: scrape
        name: Scrape
        uses: ./
